version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - checkout
      - run: <build command>
      - run:
          command: FOSSA_API_KEY=baf12d1b489b2bb33c315bfb703dd947 fossa analyze
          working_directory: https://github.com/Adityya22/Amazon_Automation
workflows:
  version: 2
  build:
    jobs:
      - build
